In [1]:
from surprise import accuracy, Dataset, SVD, similarities,AlgoBase
from surprise.model_selection import cross_validate
from surprise import BaselineOnly, Dataset, Reader
import pandas as pd

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
import datetime
import math
from surprise import Dataset
from surprise import Reader
from surprise import SVD, KNNBasic,KNNWithMeans,KNNWithZScore,KNNBaseline,SVDpp,NMF,CoClustering,accuracy,NormalPredictor
from surprise.model_selection import cross_validate
from surprise.model_selection import KFold,RepeatedKFold
from surprise.model_selection import GridSearchCV

In [2]:
import io, os, sys, setuptools, tokenize

### An issue may arise when installing scikit-surprise

https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

In [3]:
#!pip install scikit-surprise

In [3]:
feedback_orig = pd.read_csv("Feedback.csv").drop("Unnamed: 0",axis=1)
feedback_orig

     V1   V2   V3   V4   V5   V6   V7   V8   V9  V10  V11  V12  V13  V14  V15
0   3.0  NaN  NaN  3.0  NaN  3.0  3.0  NaN  NaN  3.0  3.0  NaN  4.0  NaN  3.0
1   NaN  3.0  3.0  NaN  NaN  NaN  3.0  3.0  NaN  NaN  3.0  NaN  5.0  NaN  3.0
2   NaN  NaN  3.0  3.0  3.0  3.0  3.0  3.0  NaN  NaN  NaN  4.0  3.0  3.0  NaN
3   4.0  4.0  NaN  NaN  3.0  NaN  NaN  3.0  NaN  2.0  NaN  4.0  NaN  4.0  NaN
4   5.0  NaN  5.0  5.0  NaN  NaN  5.0  NaN  5.0  NaN  NaN  5.0  NaN  NaN  5.0
5   1.0  NaN  4.0  2.0  NaN  NaN  4.0  NaN  4.0  2.0  NaN  3.0  NaN  NaN  NaN
6   NaN  NaN  3.0  4.0  NaN  3.0  NaN  NaN  3.0  NaN  1.0  5.0  NaN  NaN  3.0
7   2.0  NaN  NaN  NaN  4.0  NaN  NaN  2.0  1.0  2.0  NaN  3.0  1.0  NaN  2.0
8   3.0  NaN  3.0  NaN  NaN  5.0  NaN  3.0  3.0  NaN  3.0  NaN  3.0  4.0  3.0
9   NaN  4.0  NaN  5.0  NaN  NaN  NaN  NaN  5.0  NaN  NaN  5.0  NaN  4.0  5.0
10  NaN  3.0  3.0  3.0  5.0  3.0  NaN  3.0  NaN  NaN  NaN  NaN  NaN  NaN  3.0
11  2.0  NaN  NaN  NaN  4.0  2.0  3.0  2.0  NaN  NaN  NaN  2.0  4.0  NaN  NaN
12  NaN  3.0  5.0  5.0  3.0  NaN  NaN  5.0  4.0  NaN  NaN  NaN  5.0  3.0  NaN
13  NaN  3.0  3.0  3.0  NaN  NaN  NaN  3.0  NaN  NaN  3.0  NaN  4.0  NaN  NaN
14  NaN  NaN  NaN  NaN  3.0  2.0  NaN  2.0  NaN  2.0  NaN  2.0  NaN  2.0  2.0
15  4.0  1.0  1.0  1.0  NaN  NaN  NaN  NaN  3.0  NaN  NaN  NaN  NaN  NaN  2.0
16  NaN  NaN  NaN  2.0  NaN  2.0  NaN  2.0  NaN  1.0  1.0  NaN  5.0  NaN  NaN
17  3.0  3.0  3.0  3.0  3.0  5.0  4.0  5.0  NaN  NaN  NaN  NaN  3.0  NaN  NaN
18  NaN  4.0  NaN  NaN  NaN  NaN  4.0  3.0  NaN  NaN  5.0  NaN  NaN  NaN  3.0
19  NaN  NaN  4.0  4.0  NaN  NaN  3.0  NaN  2.0  2.0  NaN  5.0  NaN  4.0  5.0
20  NaN  1.0  3.0  3.0  NaN  NaN  NaN  5.0  1.0  5.0  1.0  2.0  NaN  4.0  3.0
21  5.0  5.0  NaN  5.0  5.0  5.0  NaN  5.0  NaN  5.0  5.0  5.0  5.0  5.0  NaN
22  NaN  4.0  4.0  NaN  NaN  1.0  5.0  2.0  NaN  NaN  3.0  NaN  NaN  2.0  NaN
23  4.0  NaN  2.0  2.0  NaN  NaN  NaN  2.0  2.0  2.0  2.0  NaN  NaN  NaN  3.0
24  3.0  NaN  3.0  NaN  NaN  3.0  NaN  NaN  5.0  NaN  2.0  5.0  NaN  4.0  NaN
25  1.0  1.0  1.0  2.0  1.0  1.0  1.0  NaN  NaN  NaN  1.0  1.0  1.0  NaN  NaN
26  5.0  NaN  NaN  3.0  NaN  NaN  NaN  3.0  NaN  3.0  NaN  NaN  5.0  3.0  3.0
27  NaN  NaN  3.0  1.0  NaN  4.0  5.0  NaN  2.0  4.0  4.0  NaN  3.0  NaN  NaN
28  NaN  NaN  3.0  NaN  3.0  NaN  3.0  NaN  5.0  5.0  3.0  NaN  NaN  NaN  NaN
29  4.0  NaN  NaN  NaN  3.0  NaN  NaN  3.0  NaN  2.0  3.0  3.0  NaN  NaN  3.0
30  2.0  NaN  4.0  NaN  3.0  NaN  2.0  NaN  1.0  NaN  NaN  3.0  2.0  2.0  NaN
31  5.0  NaN  NaN  NaN  4.0  3.0  NaN  3.0  4.0  3.0  NaN  NaN  5.0  NaN  3.0
32  NaN  NaN  4.0  NaN  NaN  3.0  NaN  NaN  2.0  NaN  5.0  NaN  2.0  2.0  NaN
33  5.0  3.0  NaN  NaN  5.0  4.0  NaN  2.0  NaN  NaN  2.0  NaN  5.0  NaN  NaN
34  NaN  4.0  3.0  4.0  NaN  NaN  NaN  2.0  5.0  NaN  4.0  4.0  3.0  NaN  NaN
35  NaN  NaN  3.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  3.0  5.0  5.0  5.0  NaN
36  5.0  NaN  3.0  NaN  NaN  3.0  NaN  3.0  5.0  3.0  NaN  NaN  3.0  NaN  3.0
37  NaN  NaN  3.0  NaN  NaN  2.0  3.0  3.0  NaN  NaN  NaN  NaN  5.0  NaN  3.0
38  NaN  3.0  NaN  4.0  5.0  NaN  NaN  3.0  5.0  3.0  3.0  NaN  5.0  NaN  1.0
39  5.0  2.0  1.0  3.0  NaN  3.0  2.0  1.0  NaN  NaN  NaN  NaN  NaN  4.0  2.0
40  5.0  3.0  NaN  3.0  5.0  4.0  3.0  3.0  NaN  NaN  NaN  4.0  3.0  NaN  NaN

### In order to use Surprise, we must reformat the data to column format, removing all NAs (?)

In [4]:
feedback_df = pd.read_csv("Feedback_reformatted.csv")
feedback_df

     User Restaurant  Rating
0       1         V1       3
1       4         V1       4
2       5         V1       5
3       6         V1       1
4       8         V1       2
..    ...        ...     ...
303    32         V9       4
304    33         V9       2
305    35         V9       5
306    37         V9       5
307    39         V9       5

[308 rows x 3 columns]

In [5]:
feedback_df = pd.read_csv("Feedback_reformatted.csv")
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(feedback_df[["User", "Restaurant", "Rating"]], reader)
data

In [401]:
# path to dataset file
#file_path = os.path.expanduser("~\\OneDrive - University of Illinois - Urbana\\STAT 542\\Feedback_formatted.csv")

# As we're loading a custom dataset, we need to define a reader. In the
# movielens-100k dataset, each line has the following format:
# 'user item rating timestamp', separated by '\t' characters.
#reader = Reader(sep=',',skip_lines=1)

#data = Dataset.load_from_file(file_path, reader=reader)

#### Split 80/20 into train/test

In [8]:
from surprise.model_selection import train_test_split as tts
trainset, testset = tts(data, test_size=0.2, random_state=42)

In [11]:
trainset

### Exploring cross-validation methods

In [9]:
# define a cross-validation iterator
kf = KFold(n_splits=3,random_state=42)

algo = SVD(random_state=42)

for trainset, testset in kf.split(data):

    # train and test algorithm.
    algo.fit(trainset)
    predictions = algo.test(testset)

    # Compute and print Root Mean Squared Error
    accuracy.rmse(predictions, verbose=True)

RMSE: 1.1134
RMSE: 1.0412
RMSE: 1.0894

In [14]:
kf = KFold(n_splits=3,random_state=42)

algo = SVD(random_state=42)

cross_validate(algo, data, measures=["RMSE", "MAE"], cv=3, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 3 split(s).

                  Fold 1  Fold 2  Fold 3  Mean    Std
RMSE (testset)    1.1015  1.1045  1.1235  1.1098  0.0098
MAE (testset)     0.8921  0.8928  0.9148  0.8999  0.0106
Fit time          0.00    0.00    0.00    0.00    0.00
Test time         0.00    0.00    0.00    0.00    0.00

{'test_rmse': array([1.10145887, 1.10454439, 1.12353468]),
 'test_mae': array([0.89209108, 0.89275229, 0.91484708]),
 'fit_time': (0.0018470287322998047,
  0.001996755599975586,
  0.0017468929290771484),
 'test_time': (0.0010159015655517578,
  0.0010061264038085938,
  0.00027561187744140625)}

In [13]:
algo = NormalPredictor()
cross_validate(algo,data,measures=["RMSE", "MAE"], cv=3)

{'test_rmse': array([1.58609293, 1.66272938, 1.61444262]),
 'test_mae': array([1.28451794, 1.33068482, 1.30934265]),
 'fit_time': (0.00038552284240722656, 0.0, 0.0),
 'test_time': (0.0, 0.0, 0.0)}

## Hyperparameter Tuning using GridSearchCV

### Description of algorithms: https://surprise.readthedocs.io/en/stable/prediction_algorithms_package.html

#### There is large variance in performance for different fold splits, so I run gridsearch 100 times and select the parameters chosen as 'best' the most times

### Tuning KNN-inspired algorithms (User-based)

In [53]:
param_grid = {"k":[10,20,40], "min_k":[1,2,4,6,8],"verbose":[False],'random_state':[42],'sim_options':{"user_based": [True],"name":['cosine','msd','pearson','pearson_baseline']}}
classes = (KNNBasic,KNNWithMeans,KNNWithZScore,KNNBaseline)
for model in classes:
    start = datetime.datetime.now()
    print(model)
    best_score = []
    best_params = [] 
    gs = GridSearchCV(model,param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
    gs.fit(data)
    print("Runtime",str(datetime.datetime.now() - start)[:-3])
    print("RMSE: ",round(gs.best_score["rmse"],3))
    print("Best parameters: ",gs.best_params["rmse"])

<class 'surprise.prediction_algorithms.knns.KNNBasic'>
Runtime 0:00:47.227
RMSE:  1.193
Best parameters:  {'k': 10, 'min_k': 8, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': True, 'name': 'msd'}}
<class 'surprise.prediction_algorithms.knns.KNNWithMeans'>
Runtime 0:00:54.185
RMSE:  1.079
Best parameters:  {'k': 40, 'min_k': 8, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': True, 'name': 'msd'}}
<class 'surprise.prediction_algorithms.knns.KNNWithZScore'>
Runtime 0:01:19.307
RMSE:  1.081
Best parameters:  {'k': 20, 'min_k': 8, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': True, 'name': 'msd'}}
<class 'surprise.prediction_algorithms.knns.KNNBaseline'>
Runtime 0:00:56.143
RMSE:  1.115
Best parameters:  {'k': 10, 'min_k': 8, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': True, 'name': 'pearson'}}

#### We select k=10, min_k=8 for basic and baseline, k=20,min_k=8 for withZScore, and k=40,min_k=8 for withMeans
#### Use mean squared distance (default) as similarity measure: https://surprise.readthedocs.io/en/stable/similarities.html#module-surprise.similarities

### Tuning KNN-inspired algorithms (Item-based)

In [55]:
param_grid = {"k":[5,8,10], "min_k":[1,2,3,4,5],"verbose":[False],'random_state':[42],'sim_options':{"user_based": [False],"name":['cosine','msd','pearson','pearson_baseline']}}
classes = (KNNBasic,KNNWithMeans,KNNWithZScore,KNNBaseline)
for model in classes:
    start = datetime.datetime.now()
    print(model)
    best_score = []
    best_params = [] 
    gs = GridSearchCV(model,param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
    gs.fit(data)
    print("Runtime",str(datetime.datetime.now() - start)[:-3])
    print("RMSE: ",round(gs.best_score["rmse"],3))
    print("Best parameters: ",gs.best_params["rmse"])

<class 'surprise.prediction_algorithms.knns.KNNBasic'>
Runtime 0:00:29.211
RMSE:  1.073
Best parameters:  {'k': 10, 'min_k': 3, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': False, 'name': 'msd'}}
<class 'surprise.prediction_algorithms.knns.KNNWithMeans'>
Runtime 0:00:32.458
RMSE:  1.074
Best parameters:  {'k': 10, 'min_k': 2, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': False, 'name': 'msd'}}
<class 'surprise.prediction_algorithms.knns.KNNWithZScore'>
Runtime 0:00:43.865
RMSE:  1.082
Best parameters:  {'k': 10, 'min_k': 2, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': False, 'name': 'msd'}}
<class 'surprise.prediction_algorithms.knns.KNNBaseline'>
Runtime 0:00:36.035
RMSE:  1.051
Best parameters:  {'k': 10, 'min_k': 4, 'verbose': False, 'random_state': 42, 'sim_options': {'user_based': False, 'name': 'msd'}}

### Tune Matrix Factorization algorithms

In [7]:
# param_grid = {"n_factors":[2,5,10,20,50,100], "n_epochs": [5,10,20,50,100,200], "lr_all": [0.001,0.002,0.005,0.01,0.02,0.05], "reg_all": [0.01,0.05,0.1,0.2,0.3,0.4,0.5],'random_state':[42],'biased':[True,False]}
param_grid = {"n_factors":[2,5,10,20,50,100], "n_epochs": [5,50,100,200], "lr_all": [0.001,0.005,0.01,0.05], "reg_all": [0.01,0.1,0.3,0.5],'random_state':[42],'biased':[True,False]}
#SVD
start = datetime.datetime.now()
best_score = []
best_params = []   
gs = GridSearchCV(SVD, param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
gs.fit(data)

print("SVD")
print("Runtime",str(datetime.datetime.now() - start)[:-3])  
print("RMSE: ",round(gs.best_score["rmse"],3))
print("Best parameters: ",gs.best_params["rmse"])

SVD
Runtime 0:17:54.503
RMSE:  1.033
Best parameters:  {'n_factors': 100, 'n_epochs': 100, 'lr_all': 0.01, 'reg_all': 0.3, 'random_state': 42, 'biased': True}

#### Try SVD with fewer factors

In [6]:
param_grid = {"n_factors":[50], "n_epochs": [50,100], "lr_all": [0.001,0.01], "reg_all": [0.01,0.1,0.3,0.5],'random_state':[42],'biased':[True,False]}
#SVD
start = datetime.datetime.now()
best_score = []
best_params = []   
gs = GridSearchCV(SVD, param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
gs.fit(data)

print("SVD")
print("Runtime",str(datetime.datetime.now() - start)[:-3])  
print("RMSE: ",round(gs.best_score["rmse"],3))
print("Best parameters: ",gs.best_params["rmse"])

SVD
Runtime 0:00:36.811
RMSE:  1.033
Best parameters:  {'n_factors': 50, 'n_epochs': 100, 'lr_all': 0.01, 'reg_all': 0.3, 'random_state': 42, 'biased': True}

In [7]:
param_grid = {"n_factors":[20], "n_epochs": [50,100], "lr_all": [0.001,0.01], "reg_all": [0.01,0.1,0.3,0.5],'random_state':[42],'biased':[True,False]}
#SVD
start = datetime.datetime.now()
best_score = []
best_params = []   
gs = GridSearchCV(SVD, param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
gs.fit(data)

print("SVD")
print("Runtime",str(datetime.datetime.now() - start)[:-3])  
print("RMSE: ",round(gs.best_score["rmse"],3))
print("Best parameters: ",gs.best_params["rmse"])

SVD
Runtime 0:00:27.986
RMSE:  1.038
Best parameters:  {'n_factors': 20, 'n_epochs': 50, 'lr_all': 0.01, 'reg_all': 0.3, 'random_state': 42, 'biased': True}

In [8]:
param_grid = {"n_factors":[10], "n_epochs": [50,100], "lr_all": [0.001,0.01], "reg_all": [0.01,0.1,0.3,0.5],'random_state':[42],'biased':[True,False]}
#SVD
start = datetime.datetime.now()
best_score = []
best_params = []   
gs = GridSearchCV(SVD, param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
gs.fit(data)

print("SVD")
print("Runtime",str(datetime.datetime.now() - start)[:-3])  
print("RMSE: ",round(gs.best_score["rmse"],3))
print("Best parameters: ",gs.best_params["rmse"])

SVD
Runtime 0:00:25.123
RMSE:  1.035
Best parameters:  {'n_factors': 10, 'n_epochs': 50, 'lr_all': 0.01, 'reg_all': 0.3, 'random_state': 42, 'biased': True}

In [8]:
#SVD++
# param_grid = {"n_epochs": [5,10,20,50,100,200], "lr_all": [0.001,0.002,0.005,0.01,0.02,0.05], "reg_all": [0.01,0.05,0.1,0.2,0.3,0.4,0.5],'random_state':[42]}
param_grid = {"n_factors":[2,5,10,20,50,100], "n_epochs": [5,50,100,200], "lr_all": [0.001,0.005,0.01,0.05], "reg_all": [0.01,0.1,0.3,0.5],'random_state':[42]}
start = datetime.datetime.now()
best_score = []
best_params = [] 
gs = GridSearchCV(SVDpp, param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
gs.fit(data)

print('SVD++')
print("Runtime",str(datetime.datetime.now() - start)[:-3])
print("RMSE: ",round(gs.best_score["rmse"],3))
print("Best parameters: ",gs.best_params["rmse"])

SVD++
Runtime 0:29:12.527
RMSE:  1.032
Best parameters:  {'n_factors': 100, 'n_epochs': 200, 'lr_all': 0.005, 'reg_all': 0.3, 'random_state': 42}

In [15]:
#Nonegative Matrix Factorization (NMF)
param_grid = {"n_factors":[2,5,10,20,50,100], 'n_epochs':[5,10,20,50,100],'reg_pu':[0.01,0.06,0.2],'reg_qi':[0.01,0.06,0.2],'biased':[True,False]}
start = datetime.datetime.now()
   
gs = GridSearchCV(NMF, param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
gs.fit(data)

print('NMF')
print("Runtime",str(datetime.datetime.now() - start)[:-3])
print("RMSE: ",round(gs.best_score["rmse"],3))
print("Best parameters: ",gs.best_params["rmse"])

NMF
Runtime 0:12:38.173
RMSE:  1.057
Best parameters:  {'n_factors': 20, 'n_epochs': 100, 'reg_pu': 0.2, 'reg_qi': 0.2, 'biased': True}

#### 'Biased' is default True for SVD and False for NMF
#### Select n_factors=100, n_epochs=200, lr_all=0.005, reg_all=0.3

### Tune co-clustering algorithms

In [626]:
param_grid = {'n_epochs':[5,10,20,50,100],'n_cltr_u':[2,3,5,8],'n_cltr_i':[2,3,5,10,20]}
start = datetime.datetime.now()
best_score = []
best_params = []
   
gs = GridSearchCV(CoClustering, param_grid, measures=["rmse", "mae"], cv=RepeatedKFold(n_splits=3,n_repeats=100))
gs.fit(data)

print('Co-clustering')
print("Runtime",str(datetime.datetime.now() - start)[:-3])
print("RMSE: ",round(gs.best_score["rmse"],3))
print("Best parameters: ",gs.best_params["rmse"])

Co-clustering
Runtime 0:10:35.811
RMSE:  1.128
Best parameters:  {'n_epochs': 20, 'n_cltr_u': 2, 'n_cltr_i': 2}

#### Select n_epochs=20, n_cltr_u=2, n_cltr_i=2

## Compare model performance

#### Mean RMSE over 1000 3-fold CVs

In [9]:
CVResults = pd.DataFrame(columns = ['Model','RMSE','MAE','Timespan'])

class PredictMean(AlgoBase):
    def __init__(self):
        AlgoBase.__init__(self)
    def estimate(self, u, i):
        return 3.237

Naive_model = PredictMean()
NormalPredictor_model = NormalPredictor()
BaselineOnly_model = BaselineOnly(verbose=False)

KNNBasic_ub_model = KNNBasic(k=10, min_k=8,verbose=False,random_state=42,sim_options={'user_based':True})
KNNBaseline_ub_model = KNNBaseline(k=40, min_k=8,verbose=False,random_state=42,sim_options={'user_based':True})
KNNWithMeans_ub_model = KNNWithMeans(k=20, min_k=8,verbose=False,random_state=42,sim_options={'user_based':True})
KNNWithZScore_ub_model = KNNWithZScore(k=10, min_k=8,verbose=False,random_state=42,sim_options={'user_based':True})
KNNBasic_ib_model = KNNBasic(k=10, min_k=3,verbose=False,random_state=42,sim_options={'user_based':False})
KNNBaseline_ib_model = KNNBaseline(k=10, min_k=2,verbose=False,random_state=42,sim_options={'user_based':False})
KNNWithMeans_ib_model = KNNWithMeans(k=10, min_k=2,verbose=False,random_state=42,sim_options={'user_based':False})
KNNWithZScore_ib_model = KNNWithZScore(k=10, min_k=4,verbose=False,random_state=42,sim_options={'user_based':False})

SVD_model = SVD(n_factors=100,n_epochs=200, lr_all=0.005, reg_all=0.3, verbose=False,random_state=42,biased=True)
SVD10_model = SVD(n_factors=10,n_epochs=50, lr_all=0.005, reg_all=0.3, verbose=False,random_state=42,biased=True)
# SVDpp_model = SVDpp(n_factors=100, n_epochs=50, lr_all=0.01, reg_all=0.3, verbose=False,random_state=42)
SVDpp_model = SVDpp(n_factors=100, n_epochs=200, lr_all=0.005, reg_all=0.3, verbose=False,random_state=42)
SVDpp10_model = SVDpp(n_factors=10, n_epochs=50, lr_all=0.005, reg_all=0.3, verbose=False,random_state=42)
NMF_model = NMF(n_epochs=20,verbose=False,random_state=42,biased=True)
CoClustering_model = CoClustering(n_epochs=20, n_cltr_u=2, n_cltr_i=2,verbose=False,random_state=42)

classes = [Naive_model,NormalPredictor_model,BaselineOnly_model,KNNBasic_ub_model,KNNBaseline_ub_model,KNNWithMeans_ub_model,KNNWithZScore_ub_model,KNNBasic_ib_model,KNNBaseline_ib_model,KNNWithMeans_ib_model,KNNWithZScore_ib_model,SVD_model,SVD10_model,SVDpp_model,SVDpp10_model,NMF_model,CoClustering_model]
for model in classes:
    start = datetime.datetime.now()
    out = cross_validate(model, data, ['rmse', 'mae'], RepeatedKFold(n_splits=3,n_repeats=1000))
    mean_rmse = np.mean(out['test_rmse'])
    mean_mae = np.mean(out['test_mae'])  
    cv_time = str(datetime.datetime.now() - start)[:-3]
    CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)

CVResults['Model'] = ['Naive','NormalPredictor','BaselineOnly','UB KNNBasic','UB KNNBaseline','UB KNNWithMeans','UB KNNWithZScore','IB KNNBasic','IB KNNBaseline','IB KNNWithMeans','IB KNNWithZScore','SVD (100 factors)','SVD (10 factors)','SVDpp (100 factors)','SVDpp (10 factors)','NMF','CoClustering']
CVResults

C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)
C:\Users\jcrul\AppData\Local\Temp\ipykernel_25596\679580653.py:37: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  CVResults = CVResults.append({'Model': model, 'RMSE': mean_rmse, 'MAE': mean_mae, 'Timespan': cv_time}, ignore_index=True)

                  Model      RMSE       MAE     Timespan
0                 Naive  1.204405  0.976973  0:00:02.654
1       NormalPredictor  1.627841  1.321161  0:00:05.032
2          BaselineOnly  1.115234  0.899873  0:00:03.327
3           UB KNNBasic  1.194078  0.955348  0:00:08.474
4        UB KNNBaseline  1.120828  0.898230  0:00:10.473
5       UB KNNWithMeans  1.082085  0.827784  0:00:09.052
6      UB KNNWithZScore  1.087400  0.828366  0:00:14.566
7           IB KNNBasic  1.071337  0.805133  0:00:04.506
8        IB KNNBaseline  1.054603  0.799692  0:00:06.425
9       IB KNNWithMeans  1.070019  0.817647  0:00:05.319
10     IB KNNWithZScore  1.099534  0.849832  0:00:07.200
11    SVD (100 factors)  1.033683  0.819913  0:00:45.590
12     SVD (10 factors)  1.043100  0.834550  0:00:08.193
13  SVDpp (100 factors)  1.031763  0.818981  0:04:10.442
14   SVDpp (10 factors)  1.041825  0.833526  0:00:19.510
15                  NMF  1.084149  0.853169  0:00:09.391
16         CoClustering  1.134868  0.870053  0:00:22.225

### Evaluate SVD predictions on one specified test set

In [71]:
from surprise.model_selection import train_test_split as tts
trainset, testset = tts(data, test_size=0.2, random_state=42)

In [72]:
predictions = SVD(n_epochs=200, lr_all=0.005, reg_all=0.3, verbose=False, random_state=42).fit(trainset).test(testset)
ResultCatcher = pd.DataFrame(predictions, columns=['User', 'Restaurant', 'Real_Rating', 'Estimated_Rating', 'details'])
ResultCatcher.drop(['details'], axis=1, inplace=True)
ResultCatcher

    User Restaurant  Real_Rating  Estimated_Rating
0     14         V8          3.0          3.153624
1     26         V4          2.0          1.484804
2     30         V1          4.0          3.280600
3     23        V11          3.0          3.295759
4     33        V13          2.0          3.344531
..   ...        ...          ...               ...
57    10         V4          5.0          4.193041
58    25        V12          5.0          3.746991
59    13        V14          3.0          3.944298
60    15         V8          2.0          2.286018
61     3        V14          3.0          3.325386

[62 rows x 4 columns]

In [73]:
print('MAE:',round(accuracy.mae(predictions),3))
print('RMSE:',round(accuracy.rmse(predictions),3))

MAE:  0.7682
MAE: 0.768
RMSE: 0.9643
RMSE: 0.964

### Compare with naive estimator (just the mean)

In [75]:
class PredictMean(AlgoBase):
    def __init__(self):
        AlgoBase.__init__(self)
    def estimate(self, u, i):
        return 3.237

predictions = PredictMean().fit(trainset).test(testset)
print('MAE:',round(accuracy.mae(predictions),3))
print('RMSE:',round(accuracy.rmse(predictions),3))

MAE:  1.0026
MAE: 1.003
RMSE: 1.2417
RMSE: 1.242

#### MSE with SVD is (0.9643/1.2417)^2 = 60.31% of the naive estimator

### Analyze accuracy of SVD predictions on population segments

In [636]:
ResultComparison = pd.DataFrame({'Count': ResultCatcher.groupby(['Real_Rating']).size(),
        'Avg_Est': ResultCatcher.groupby(['Real_Rating']).mean()['Estimated_Rating']
        }).reset_index()
ResultComparison

C:\Users\jcrul\AppData\Local\Temp\ipykernel_30272\3484432280.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  'Avg_Est': ResultCatcher.groupby(['Real_Rating']).mean()['Estimated_Rating']

   Real_Rating  Count   Avg_Est
0          1.0      7  2.189452
1          2.0     12  2.789653
2          3.0     25  3.289865
3          4.0      6  3.411117
4          5.0     12  3.789092

#### Tends to overestimate low ratings and underestimate high ratings

### Confirm that we may predict missing values

In [77]:
algo = SVD(n_epochs=5, lr_all=0.001, reg_all=0.2, verbose=False, random_state=42).fit(trainset)
pred = algo.predict(uid=2, iid='V1', verbose=True)

user: 2          item: V1         r_ui = None   est = 3.26   {'was_impossible': False}

## Next Steps:
### Confirm missing values were handled correctly
### Figure out how to submit predictions

#### Evaluate on the entire dataset

In [6]:
all_dataset = data.build_full_trainset()
model = SVD(n_epochs=200, lr_all=0.005, reg_all=0.3, verbose=False, random_state=42).fit(all_dataset)

In [8]:
feedback_pred = feedback_orig.copy()

In [9]:
for v in feedback_pred.columns:
    for i in feedback_pred.index:
        val = feedback_pred.iloc[i][v]
        if pd.isnull(val):
            feedback_pred.iloc[i][v] = model.predict(uid=i+1, iid=v, verbose=False).est

In [10]:
feedback_pred

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15
0,3.000000,2.915125,3.096318,3.000000,3.491074,3.000000,3.000000,2.998170,3.231718,3.000000,3.000000,3.488151,4.000000,3.223453,3.000000
1,3.904623,3.000000,3.000000,3.359263,3.775469,3.227723,3.000000,3.000000,3.673800,3.095216,3.000000,3.760955,5.000000,3.567399,3.000000
2,3.337861,2.854548,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.105340,2.873284,2.855822,4.000000,3.000000,3.000000,2.964254
3,4.000000,4.000000,3.247250,3.316952,3.000000,3.164566,3.411835,3.000000,3.567330,2.000000,3.078502,4.000000,3.792723,4.000000,3.199202
4,5.000000,4.366082,5.000000,5.000000,4.787959,4.307359,5.000000,4.262825,5.000000,4.148570,4.263347,5.000000,4.852598,4.464221,5.000000
5,1.000000,2.931339,4.000000,2.000000,3.117857,2.658271,4.000000,2.827705,4.000000,2.000000,2.931245,3.000000,3.084720,2.660475,2.870490
6,3.637396,2.853405,3.000000,4.000000,3.565103,3.000000,3.053452,3.007353,3.000000,2.901351,1.000000,5.000000,3.842731,3.489402,3.000000
7,2.000000,2.216213,2.491548,2.196496,4.000000,2.475243,2.594261,2.000000,1.000000,2.000000,2.455727,3.000000,1.000000,2.347648,2.000000
8,3.000000,2.960113,3.000000,3.162362,3.640746,5.000000,3.334216,3.000000,3.000000,3.299491,3.000000,3.604268,3.000000,4.000000,3.000000
9,4.535697,4.000000,4.217504,5.000000,4.543128,4.090026,4.273468,4.026073,5.000000,3.927606,3.953727,5.000000,4.658460,4.000000,5.000000
10,3.791198,3.000000,3.000000,3.000000,5.000000,3.000000,3.369843,3.000000,3.440957,3.077644,3.058501,3.685937,3.724713,3.461797,3.000000
11,2.000000,2.541966,2.721672,2.672311,4.000000,2.000000,3.000000,2.000000,2.839554,2.407563,2.433278,2.000000,4.000000,2.710197,2.513181
12,3.866371,3.000000,5.000000,5.000000,3.000000,3.712313,3.971225,5.000000,4.000000,3.736013,3.552908,4.166436,5.000000,3.000000,3.851809
13,3.643227,3.000000,3.000000,3.000000,3.616970,3.168933,3.298321,3.000000,3.373081,3.025439,3.000000,3.599315,4.000000,3.357348,3.074222
14,2.715628,2.249903,2.390546,2.339064,3.000000,2.000000,2.553896,2.000000,2.504231,2.000000,2.262455,2.000000,2.770491,2.000000,2.000000
15,4.000000,1.000000,1.000000,1.000000,2.850529,2.433952,2.195488,1.988374,3.000000,2.256559,1.824281,2.672841,2.908510,2.753821,2.000000
16,3.242767,2.311538,2.286300,2.000000,3.057201,2.000000,2.471074,2.000000,3.069443,1.000000,1.000000,3.086591,5.000000,2.809314,2.278367
17,3.000000,3.000000,3.000000,3.000000,3.000000,5.000000,4.000000,5.000000,3.131593,3.629279,3.337069,3.675959,3.000000,3.567172,3.476017
18,3.983910,4.000000,3.700328,3.535979,4.136878,3.558479,4.000000,3.000000,3.789088,3.357387,5.000000,3.972655,3.796869,3.529161,3.000000
19,3.661229,3.351222,4.000000,4.000000,3.879078,3.477064,3.000000,3.439340,2.000000,2.000000,3.253933,5.000000,3.752732,4.000000,5.000000
20,3.047576,1.000000,3.000000,3.000000,3.128208,3.336730,2.865491,5.000000,1.000000,5.000000,1.000000,2.000000,3.156629,4.000000,3.000000
21,5.000000,5.000000,4.477945,5.000000,5.000000,5.000000,4.621337,5.000000,4.583083,5.000000,5.000000,5.000000,5.000000,5.000000,4.420852
22,3.124687,4.000000,4.000000,3.051882,3.459261,1.000000,5.000000,2.000000,3.304040,2.453127,3.000000,3.438850,3.434220,2.000000,2.972287
23,4.000000,2.368670,2.000000,2.000000,3.141070,2.641314,2.652716,2.000000,2.000000,2.000000,2.000000,3.039077,3.066635,2.849269,3.000000
24,3.000000,3.182234,3.000000,3.542483,3.734962,3.000000,3.338858,3.127757,5.000000,3.090769,2.000000,5.000000,4.120680,4.000000,3.201929
25,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.566225,1.528898,1.517072,1.000000,1.000000,1.000000,1.634188,1.479895
26,5.000000,3.202097,3.164281,3.000000,3.911353,3.257523,3.422226,3.000000,3.812631,3.000000,3.029256,3.841238,5.000000,3.000000,3.000000
27,3.356296,3.010536,3.000000,1.000000,3.613407,4.000000,5.000000,3.311645,2.000000,4.000000,4.000000,3.378890,3.000000,3.238666,3.224057
28,4.051597,3.170774,3.000000,3.605049,3.000000,3.589737,3.000000,3.455426,5.000000,5.000000,3.000000,3.897280,4.072984,3.837666,3.291331
29,4.000000,2.850098,2.942353,2.978631,3.000000,2.923996,3.105181,3.000000,3.172074,2.000000,3.000000,3.000000,3.435488,3.088851,3.000000
30,2.000000,2.379377,4.000000,2.477264,3.000000,2.569841,2.000000,2.650791,1.000000,2.415621,2.580963,3.000000,2.000000,2.000000,2.654846
31,5.000000,3.308532,3.254848,3.510406,4.000000,3.000000,3.492137,3.000000,4.000000,3.000000,3.081532,3.965197,5.000000,3.710908,3.000000
32,2.862520,3.168308,4.000000,2.893266,3.371315,3.000000,3.578350,3.097950,2.000000,2.919460,5.000000,3.251975,2.000000,2.000000,3.182638
33,5.000000,3.000000,3.054246,3.483146,5.000000,4.000000,3.321568,2.000000,3.962878,3.146881,2.000000,4.016880,5.000000,3.910542,3.159229
34,3.957301,4.000000,3.000000,4.000000,3.924034,3.294456,3.586542,2.000000,5.000000,3.078935,4.000000,4.000000,3.000000,3.477553,3.210442
35,4.566866,3.501847,3.000000,3.871873,4.319119,3.836061,3.701367,3.568986,4.259165,3.624683,3.000000,5.000000,5.000000,5.000000,3.621210
36,5.000000,3.254971,3.000000,3.389485,3.853189,3.000000,3.412464,3.000000,5.000000,3.000000,3.157261,3.853696,3.000000,3.558903,3.000000
37,3.654940,2.965665,3.000000,3.253057,3.578463,2.000000,3.000000,3.000000,3.580708,2.823953,2.658957,3.605243,5.000000,3.313391,3.000000
38,4.228656,3.000000,3.119679,4.000000,5.000000,3.234087,3.390968,3.000000,5.000000,3.000000,3.000000,3.911461,5.000000,3.705671,1.000000
39,5.000000,2.000000,1.000000,3.000000,3.400596,3.000000,2.000000,1.000000,3.281713,2.514218,2.158828,3.242769,3.501014,4.000000,2.000000
40,5.000000,3.000000,3.199327,3.000000,5.000000,4.000000,3.000000,3.000000,3.526319,3.286153,3.224973,4.000000,3.000000,3.684354,3.247767

In [11]:
feedback_pred.to_csv('Feedback_pred.csv')